config/routes.rb
Rails.application.routes.draw do
  get "orders/new"
  get "orders/create"
  get "carts/show"
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get "admin/dashboard"
  get "new/create"
  get "home/index"

  # Для здоров'я програми
  get "up" => "rails/health#show", as: :rails_health_check

  # Для PWA
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get 'admin', to: 'admin#dashboard'
  get '/cart', to: 'carts#show', as: 'cart'
  get 'my_cart', to: 'carts#show', as: 'my_cart'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  
  resources :orders, only: [:new, :create]
  get 'user/orders', to: 'orders#user_orders', as: 'user_orders'
  # Головний маршрут
  root "home#index" 

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]


  resources :feedbacks, only: [:index, :new, :create]

  resources :orders, only: [:new, :create]
  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  # Якщо корзина порожня, то ми створюємо нову
  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(product_id: product.id, quantity: 1)
    end
    current_item.save
  end
  def update_quantity(product, quantity)
    cart_item = cart_items.find_by(product: product)
    cart_item.update(quantity: quantity)
  end

  def remove_item(product)
    cart_item = cart_items.find_by(product: product)
    cart_item.destroy if cart_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart
    @cart_items = @cart.cart_items.includes(:product)
  end
  def update
    @cart = current_cart
    product = Product.find(params[:product_id])
    quantity = params[:quantity].to_i

    if quantity > 0
      @cart.update_quantity(product, quantity)
    else
      @cart.remove_item(product)
    end

    redirect_to cart_path
  end
  def destroy
    @cart = current_cart
    product = Product.find(params[:product_id])

    @cart.remove_item(product)

    redirect_to cart_path
  end

    private

    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h1>Моя корзина</h1>
<link rel="stylesheet" type="text/css" href="<%= asset_path('cart_style.css') %>">

<% if @cart.cart_items.any? %>
  <table class="cart-table">
    <thead>
      <tr>
        <th>Товар</th>
        <th>Кількість</th>
        <th>Ціна</th>
        <th>Загальна ціна</th>
        <th>Дії</th>
      </tr>
    </thead>
    <tbody> 
      <% @cart.cart_items.each do |cart_item| %>
        <% if cart_item.product.present? %>  <!-- Перевірка на наявність продукту -->
          <tr id="cart-item-<%= cart_item.id %>">
            <td><%= cart_item.product.name %> - <%= cart_item.product.price %> грн</td>
            <td>
              <%= form_for cart_item, url: cart_cart_item_path(cart_item) do |f| %>
                <%= f.number_field :quantity, value: cart_item.quantity, min: 1, max: 100 %>
                <%= f.submit 'Оновити', class: 'btn btn-primary' %>
              <% end %>
            </td>
            <td class="price"><%= cart_item.product.price %></td>

            <td class="total-price"><%= cart_item.quantity * cart_item.product.price %></td>

            <td>
              <%= form_with model: cart_item, url: cart_cart_item_path(cart_item), method: :delete do |form| %>
                <%= form.submit 'Видалити', class: 'btn btn-danger' %>
              <% end %>
            </td>
          </tr>
        <% else %>  <!-- Якщо продукт відсутній -->
          <tr>
           
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <h3>Всього: <%= number_to_currency(@cart.cart_items.sum { |item| item.product.present? ? item.quantity * item.product.price : 0 }, unit: "₴", format: "%u %n") %></h3>  <%= link_to 'Оформити замовлення', new_order_path, class: 'btn btn-success' %>
<% else %>
  <p>У вашій корзині немає товарів.</p>
<% end %>

<%= link_to 'Продовжити покупки', products_path %>